defaults:
  - _self_
  - model: cocondenser

seed: 1776

data:
  name: "jturner116/msmarco-hard-negatives-scored-stella"
  split: "train"

use_distillation: True
custom_kernel: True
batch_size: 4
num_negatives: 6
lambda_d: 9e-4
lambda_q: 5e-4
T_d: 8000
T_q: 8000
top_k: 256
epochs: 5

optimizer:
  learning_rate: 5e-6
  warmup_steps: 2000
  weight_decay: 0.01
  every_k_schedule: 4

checkpoint:
  max_to_keep: 5
  save_interval_steps: 800
  checkpoint_path: "checkpoints/cocondenser"
evaluation:
  eval_every_steps: 800
  datasets: ["scifact", "quoraretrieval", "msmarco"]
  batch_size: 16
wandb: True
wandb_project: "splade-cocondensor"
log_every: 20

