defaults:
  - _self_
  - model: cocondenser

seed: 1776

data:
  name: "jturner116/msmarco-hard-negatives-scored-stella"
  split: "train"

use_distillation: True
custom_kernel: True
batch_size: 32
mini_batch: 64
num_negatives: 32
sample_size: 16
n_ways: 32
proximity_threshold: 0.05
max_length: 256
lambda_d: 0.002
lambda_q: 0.002
T_d: 1000
T_q: 1000
T_d_start: 0
T_q_start: 0
top_k: null
epochs: 5
sparse_embed: False
init_ce_temp: null
init_kl_temp: null
optimizer:
  learning_rate: 2e-4
  warmup_steps: 200
  grad_clip_warmup_steps: 800
  weight_decay: 0.01
  max_grad_norm: 15.0
checkpoint:
  max_to_keep: 3
  save_interval_steps: 800
  checkpoint_path: "checkpoints/cocondenser"
evaluation:
  eval_every_steps: 300
  datasets: ["scifact", "quoraretrieval", "msmarco", "touche2020", "scidocs", "nfcorpus"]
  batch_size: 16
wandb: True
wandb_project: "splade-cocondensor"
log_every: 20

