defaults:
  - _self_
  - model: cocondenser

seed: 1776

data:
  name: "jturner116/msmarco-hard-negatives-scored-stella"
  split: "train"

use_distillation: True
custom_kernel: True
batch_size: 16
mini_batch: 2
num_negatives: 32
max_length: 256
lambda_d: 9e-4
lambda_q: 5e-4
T_d: 20000
T_q: 20000
T_d_start: 5000
T_q_start: 5000
top_k: 128
epochs: 5
sparse_embed: False

optimizer:
  learning_rate: 8e-5
  warmup_steps: 2000
  weight_decay: 0.00
  every_k_schedule: 4

checkpoint:
  max_to_keep: 3
  save_interval_steps: 800
  checkpoint_path: "checkpoints/cocondenser"
evaluation:
  eval_every_steps: 200
  datasets: ["scifact", "quoraretrieval", "msmarco", "touche2020", "scidocs", "nfcorpus"]
  batch_size: 16
wandb: True
wandb_project: "splade-cocondensor"
log_every: 20

