defaults:
  - _self_
  - model: cocondenser

seed: 1776

data:
  format: "json"
  train_path: "/root/data/msmarco_triplets/msmarco-triplets-scored-fp32.jsonl.gz"

use_distillation: True
batch_size: 12
num_negatives: 8
lambda_d: 9e-4
lambda_q: 5e-4
T_d: 8000
T_q: 8000
top_k: 256
epochs: 5

optimizer:
  learning_rate: 3e-6
  warmup_steps: 2000
  every_k_schedule: 4
  weight_decay: 0.01
checkpoint:
  max_to_keep: 5
  save_interval_steps: 800
  checkpoint_path: "checkpoints/modernbert"
evaluation:
  eval_every_steps: 400
  datasets: ["scifact", "quoraretrieval", "msmarco"]
  batch_size: 16
wandb: True
wandb_project: "splade-modernbert"
log_every: 20



