defaults:
  - _self_
  - model: modernbert

seed: 1776

data:
  name: "jturner116/msmarco-hard-negatives-scored-stella"
  split: "train"

use_distillation: True
custom_kernel: True
use_grad_cache: False
bf16: True
accum_steps: 4
batch_size: 8
mini_batch: 64
num_negatives: 32
sample_size: 8
n_ways: null
proximity_threshold: 0.05
mse_weight: 0.05
kl_weight: 1.0
max_length: 256
lambda_d: 5.0e-4
lambda_q: 5.0e-4
T_d: 50000
T_q: 50000
# Top-k scheduling
top_k: null
schedule_top_k: False
initial_top_k: 50000
top_k_warmup_steps: 40000
epochs: 20
sparse_embed: False
init_ce_temp: null
init_kl_temp: null
optimizer:
  learning_rate: 6e-5
  warmup_steps: 5000
  grad_clip_warmup_steps: 6000
  weight_decay: 0.00
  decay_steps: 50000
  stable_steps: 280000
  max_grad_norm: null
  rep_grad_clip: null
checkpoint:
  max_to_keep: 3
  save_interval_steps: 800
  checkpoint_path: "checkpoints/modernbert"
evaluation:
  eval_every_steps: 2000
  datasets: ["scifact", "quoraretrieval", "msmarco", "touche2020", "scidocs", "nfcorpus"]
  batch_size: 16
wandb: True
wandb_project: "splade-modernbert"
log_every: 20


