defaults:
  - _self_
  - model: modernbert

seed: 1776

data:
  name: "jturner116/msmarco-hard-negatives-scored-stella"
  split: "train"

use_distillation: True
custom_kernel: True
batch_size: 48
mini_batch: 6
num_negatives: 12
max_length: 256
lambda_d: 9e-4
lambda_q: 5e-4
T_d: 16000
T_q: 16000
T_d_start: 5000
T_q_start: 5000
top_k: 128
epochs: 9
sparse_embed: False

optimizer:
  learning_rate: 6e-5
  warmup_steps: 2000
  every_k_schedule: 4
  weight_decay: 0
checkpoint:
  max_to_keep: 5
  save_interval_steps: 1200
  checkpoint_path: "checkpoints/modernbert"
evaluation:
  eval_every_steps: 800
  datasets: ["scifact", "quoraretrieval", "msmarco", "touche2020", "scidocs", "nfcorpus"]
  batch_size: 16
wandb: True
wandb_project: "splade-modernbert"
log_every: 20



