defaults:
  - _self_
  - model: neo

seed: 1776

data:
  name: "jturner116/msmarco-hard-negatives-scored-stella"
  split: "train"

use_distillation: True
teacher_model: "naver/splade-v3"
custom_kernel: True
use_grad_cache: False
bf16: True
accum_steps: 2
batch_size: 8
mini_batch: 64
num_negatives: 32
sample_size: 8
n_ways: null
top_k: 256
proximity_threshold: 0.05
max_length: 512
epochs: 20
sparse_embed: False
optimizer:
  learning_rate: 3e-5
  warmup_steps: 10000
  grad_clip_warmup_steps: 6000
  weight_decay: 0.00
  decay_steps: 50000
  stable_steps: 40000
  max_grad_norm: null
  rep_grad_clip: null
checkpoint:
  max_to_keep: 3
  save_interval_steps: 800
  checkpoint_path: "checkpoints/neo-distil"
evaluation:
  eval_every_steps: 1000
  datasets: ["scifact", "quoraretrieval", "msmarco", "touche2020", "scidocs", "nfcorpus"]
  batch_size: 16
wandb: True
wandb_project: "splade-neo-distil"
log_every: 20


